const brandData = [
    {id: 0,
     name: 'Belvoir',
     logoImage: './assets/assetsLogo/BFFLogo.png',
     brand: 'Belvoir Fruit Farms',
     desc1: `Belvoir Fruit Farms nestles deep in the English countryside. For over 35 years, in the idyllic Vale of Belvoir, they've been pressing fresh fruit & infusing flowers to mix with spring water to make their fruit cordials & presses.`,   
     desc2: `Renowned for their elderflower drinks, still made to the original family recipe, the expanded range offers a wide variety of natural & authentic flavours. Locally, Belvoir Fruit Farms is ranged by both Coles & Woolworths.`,
     creative: './assets/assetsCreative/BFFCreative.png',
     brief: `Devise a strategy to educate consumers on a product form not previously seen in the local market to mitigate the potential threat of de-listing. The strategy should also have a halo effect on the brand's core range. Manage the execution of the approved strategy locally on behalf of the brand.`,
     solution1: ``,   
     solution2: '',
     solution3: '',
    },
    {id: 1,
     name: 'Thorburn',
     logoImage: './assets/assetsLogo/ThorburnLogo.png',
     brand: 'Thorburn Property',
     desc1: `Thorburn Property is a boutique commercial real estate agency located in Melbourne.`,  
     desc2: `They specialise in the leasing of office property in the city fringe, with a particular focus on the St Kilda Rd market & surrounding suburbs.`,   
     creative: './assets/assetsCreative/ThorburnCreative.jpg',
     brief: `Enhance the provided content to create a tender winning presentation that showcases the professionalism and expertise behind the brand.`,
     solution1: `After carefully disseminating the client provided content and researching the competitive landscape and market, a reverse brief was presented to Thorburn Property for their approval.`,
     solution2: `They happily accepted the recommendations for additional content inclusions designed to position their brand in the market and highlight their USP and suitability for the business being tendered.`,
     solution3: 'Managing all elements of design, production and delivery on their behalf, the project was delivered in full, on time and to budget.  It also resulted in Thorburn Property being successfful in winning the tender, augmenting their standing in the market, and creating further potential for the brand.',
    },
    {id: 2,
        name: 'ATT',
        logoImage: './assets/assetsLogo/ATTLogo.png',
        brand: 'Ask The Tarot',
        desc1: ``,   
        desc2: ``,
        creative: '',
        brief: '',
        solution1: '',   
        solution2: '',
        solution3: '',
       },
       {id: 3,
        name: 'Infrusion',
        logoImage: './assets/assetsLogo/LogoInfrusion.png',
        brand: 'Infrusion',
        desc1: ``,  
        desc2: ``,   
        creative: './assets/assetsCreative/InfrusionCreative.jpg',
        brief: 'still to come',
        solution1: 'still to come',
        solution2: 'still to come',
        solution3: 'sitll to come',
       },
       {id: 4,
        name: 'RBY',
        logoImage: './assets/assetsLogo/RBYLogo.png',
        brand: 'Reboot You',
        desc1: ``,   
        desc2: ``,
        creative: './assets/assetsCreative/RBYCreative.png',
        brief: '',
        solution1: '',   
        solution2: '',
        solution3: '',
       },
       {id: 5,
        name: 'tshirts',
        logoImage: './assets/assetsLogo/tshirtsonlineLogo.png',
        brand: 'tshirtsonline.com.au',
        desc1: ``,  
        desc2: ``,   
        creative: './assets/assetsCreative/tshirtsonlineCreative.png',
        brief: 'still to come',
        solution1: 'still to come',
        solution2: 'still to come',
        solution3: 'sitll to come',
       },
       {id: 6,
        name: 'SAS',
        logoImage: './assets/assetsLogo/LogoSAS.png',
        brand: 'Shepherd Advisory Service',
        desc1: ``,   
        desc2: ``,
        creative: './assets/assetsCreative/ShepherdCreative.png',
        brief: '',
        solution1: '',   
        solution2: '',
        solution3: '',
       },
       {id: 7,
        name: 'LadyBoss',
        logoImage: './assets/assetsLogo/LogoLadyBoss.png',
        brand: 'Lady Boss',
        desc1: ``,  
        desc2: ``,   
        creative: './assets/assetsCreative/LadyBossCreative.png',
        brief: 'still to come',
        solution1: 'still to come',
        solution2: 'still to come',
        solution3: 'sitll to come',
       },
       {id: 8,
        name: 'Balance',
        logoImage: './assets/assetsLogo/LogoBalance.png',
        brand: 'Balance Commercial Furniture & Interiors',
        desc1: `Since 2004, Balance Commercial Furniture & Interiors has been meeting the needs of both public & private sector organisations with respect to their office furniture & fit out requirements.`,  
        desc2: `Their extensive network of suppliers and trades excludes "middle-men" allowing them to offer shortened timeframes without compromising on quality.`,   
        creative: './assets/assetsCreative/LadyBossCreative.png',
        brief: 'Build brand awareness within the target market. Position the brand as experts in creating contemporary spaces promoting productivity, health and well-being. Generate brand interactions.',
        solution1: `Balance was keen to see an immediate response to their marketing efforts. Leveraging the insights uncovered while researching the market, a mix of broadcast and digital was agreed as the most cost effective way to achieve the set objectives.`,
        solution2: 'Booking a heavily strategised radio schedule as the first wave of the campaign delivered the brand awareness required for the second wave to deliver. A highly targeted digital campaign, run exclusively via one platform allowed the brand to initiate a personalised dialogue with potential new customers.',
        solution3: `Measuring web traffic via an attribution model, the broadcast campaign increased visits by 50% whilst active. Achieving a CTR of 1.02% on sponsored content was aided by the broadcast efforts. Personalisaton of message, timing and careful targeting delivered a CTR of 50.9% for the second digital campaign component. An analysis of the data generated by the campaign was converted into actionable insights and included in the post campaign report for Balance to leverage in a manner of their choosing.`,
       },
       {id: 9,
        name: 'TGFM',
        logoImage: './assets/assetsLogo/LogoTGFM.png',
        brand: 'That Guy From Marketing&reg;',
        desc1: ``,
        desc2: ``,   
        creative: './assets/assetsCreative/LadyBossCreative.png',
        brief: 'still to come',
        solution1: 'still to come',
        solution2: 'still to come',
        solution3: 'sitll to come',
       },
]

